[tools]
uv = "latest"

[tasks.lint]
description = "Run static code analysis"
run = [
    'uv run ruff format src',
    'uv run ruff check --fix src',
    'uv run pyright src',
]

[tasks.server]
description = 'Run the API HTTP server'
run = 'uv run library-api'
